org: antonioevaldo
app: escola-serverless
service: api
frameworkVersion: '3'

custom:
  nomeBucketCsv: alunos-csv
  host: localhost
  directory: /temp

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  iam:
    role:
      statements:
        # Allow functions to read objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
          Resource:
            - 'arn:aws:s3:::${self:custom.nomeBucketCsv}/*'

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: bucket-local

functions:
  simulandoUploadDeBucket:
    handler: api/index.simulandoUploadDeBucket
    events:
      - httpApi:
          method: post
          path: /alunos/batch

  cadastrarAlunos:
    handler: api/index.cadastrarAlunos
    events:
      - s3:
          bucket: bucket-local
          event: s3:ObjectCreated:*

plugins:
  - serverless-offline
  - serverless-s3-local
