org: antonioevaldo
app: escola-serverless
service: api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  iam:
    role:
      statements:
        # Allow functions to read objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
          Resource:
            - 'arn:aws:s3:::alunos-csv/*'

functions:
  simulandoUploadDeBucket:
    handler: api/bucket-local/index.simulandoUploadDeBucket
    events:
      - httpApi:
          method: post
          path: /alunos/batch
    enabled: false

  cadastrarAlunosDoBucketLocal:
    handler: api/bucket-local/index.cadastrarAlunos
    events:
      - s3:
          bucket: bucket-local
          event: s3:ObjectCreated:*
    enabled: false

  cadastrarAlunos:
    handler: api/bucket-aws/index.cadastrarAlunos
    events:
      - s3:
          bucket: alunos-csv
          event: s3:ObjectCreated:*

package: 
  exclude:
    - simulandoUploadDeBucket
    - cadastrarAlunosDoBucketLocal

plugins:
  - serverless-offline
  - serverless-s3-local
  - serverless-disable-functions
